// Mock profile data for development / demo
// Replace with real Firestore queries in production.

import type { ProfileCardData } from '@/types/matrimony';

export const MOCK_PROFILES: ProfileCardData[] = [
  {
    id: 'profile-001',
    fullName: 'Priya Golchha',
    age: 26,
    heightCm: 163,
    maritalStatus: 'never_married',
    currentCity: 'Jaipur',
    currentState: 'Rajasthan',
    occupation: 'professional',
    annualIncomeRange: '10-20L',
    highestQualification: 'CA',
    subSect: 'digambar',
    subSectBranch: 'mandir',
    paternalGotra: 'Golchha',
    maternalGotra: 'Nahar',
    diet: 'jain_no_root',
    familyType: 'joint',
    manglikStatus: 'no',
    profilePhotoUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&q=80',
    aboutMe: 'A Chartered Accountant by profession, I love classical music and traveling to Jain pilgrimage sites. Looking for a well-educated, family-oriented partner who shares our cultural values.',
    verificationStatus: 'verified',
    willingToRelocate: true,
  },
  {
    id: 'profile-002',
    fullName: 'Ankita Jain',
    age: 24,
    heightCm: 158,
    maritalStatus: 'never_married',
    currentCity: 'Mumbai',
    currentState: 'Maharashtra',
    occupation: 'private_job',
    annualIncomeRange: '5-10L',
    highestQualification: 'MBA',
    subSect: 'shwetambar',
    subSectBranch: 'sthanak',
    paternalGotra: 'Chopda',
    maternalGotra: 'Surana',
    diet: 'strict_chauvihar',
    familyType: 'nuclear',
    manglikStatus: 'dont_know',
    profilePhotoUrl: 'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?w=400&q=80',
    aboutMe: 'An MBA graduate working in digital marketing at a leading firm. I enjoy reading, cooking traditional Jain recipes, and yoga. Family values are paramount to me.',
    verificationStatus: 'verified',
    willingToRelocate: false,
  },
  {
    id: 'profile-003',
    fullName: 'Deepika Mehta',
    age: 28,
    heightCm: 166,
    maritalStatus: 'never_married',
    currentCity: 'Ahmedabad',
    currentState: 'Gujarat',
    occupation: 'business',
    annualIncomeRange: '20-50L',
    highestQualification: 'B.Com',
    subSect: 'shwetambar',
    subSectBranch: 'mandir',
    paternalGotra: 'Lodha',
    maternalGotra: 'Doshi',
    diet: 'jain_no_root',
    familyType: 'joint',
    manglikStatus: 'no',
    profilePhotoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&q=80',
    aboutMe: 'Running a family textile business in Ahmedabad. I believe in balancing career and family traditions beautifully.',
    verificationStatus: 'verified',
    willingToRelocate: true,
  },
  {
    id: 'profile-004',
    fullName: 'Ritu Patni',
    age: 25,
    heightCm: 160,
    maritalStatus: 'never_married',
    currentCity: 'Pune',
    currentState: 'Maharashtra',
    occupation: 'private_job',
    annualIncomeRange: '5-10L',
    highestQualification: 'B.Tech',
    subSect: 'digambar',
    subSectBranch: 'mandir',
    paternalGotra: 'Kasliwal',
    maternalGotra: 'Sethiya',
    diet: 'regular_veg',
    familyType: 'nuclear',
    manglikStatus: 'yes',
    profilePhotoUrl: 'https://images.unsplash.com/photo-1601412436009-d964bd02edbc?w=400&q=80',
    aboutMe: 'Software engineer passionate about technology and Jain philosophy. I volunteer at paryushan events every year.',
    verificationStatus: 'pending',
    willingToRelocate: true,
  },
];

// Male profiles (for completeness)
export const MOCK_MALE_PROFILES: ProfileCardData[] = [
  {
    id: 'profile-m001',
    fullName: 'Aryan Kothari',
    age: 29,
    heightCm: 177,
    maritalStatus: 'never_married',
    currentCity: 'Delhi',
    currentState: 'Delhi',
    occupation: 'professional',
    annualIncomeRange: '20-50L',
    highestQualification: 'MBA',
    subSect: 'digambar',
    subSectBranch: 'mandir',
    paternalGotra: 'Kothari',
    maternalGotra: 'Baid',
    diet: 'jain_no_root',
    familyType: 'joint',
    manglikStatus: 'no',
    profilePhotoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
    aboutMe: 'Investment banker by profession, Jain by heart. I enjoy cricket, trekking, and participating in community events.',
    verificationStatus: 'verified',
    willingToRelocate: true,
  },
  {
    id: 'profile-m002',
    fullName: 'Vivek Saklecha',
    age: 27,
    heightCm: 173,
    maritalStatus: 'never_married',
    currentCity: 'Jaipur',
    currentState: 'Rajasthan',
    occupation: 'business',
    annualIncomeRange: '10-20L',
    highestQualification: 'B.Com',
    subSect: 'shwetambar',
    subSectBranch: 'sthanak',
    paternalGotra: 'Saklecha',
    maternalGotra: 'Bafna',
    diet: 'strict_chauvihar',
    familyType: 'joint',
    manglikStatus: 'no',
    profilePhotoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80',
    aboutMe: 'Managing a family business in gems & jewellery. Active in Jain community events and paryushan puja.',
    verificationStatus: 'verified',
    willingToRelocate: false,
  },
];
